ALTER TABLE inventory_movements
    DROP CONSTRAINT "fk_receipt",
    ADD CONSTRAINT CONSTRAINT "fk_receipt" FOREIGN KEY ("receipt_id") REFERENCES "receipts" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
